#!/usr/bin/env bash
#
# Extracts the Granulator DSP class from the LV2 build that ships in CppSrc/
# and wraps it in a minimal shim so it can be instantiated on its own.
#
# That file was generated by Faust 2.0.a40 in 2016 and is what actually runs on
# the MOD, which makes it the reference for how the plugin is supposed to sound.
# The desktop build regenerates the same .dsp with a current Faust, and the
# comparison test uses this extract to prove the two still agree.
#
# The output is committed, so this only needs re-running if CppSrc/ is ever
# regenerated. Nothing here should be edited by hand.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE="$ROOT/CppSrc/Granulator_linux_lv2-32bits.cpp"
OUTPUT="$ROOT/Plugins/Tests/reference/LegacyGranulator.hpp"

if [ ! -f "$SOURCE" ]; then
    echo "error: $SOURCE not found" >&2
    exit 1
fi

# The class and its table-filling helper, located rather than hard coded so the
# script survives edits above them in the file.
FIRST=$(grep -n '^class GranulatorSIG0' "$SOURCE" | head -1 | cut -d: -f1)
LAST=$(awk 'NR>'"$FIRST"' && /^};/ { count++; if (count==2) { print NR; exit } }' "$SOURCE")

if [ -z "$FIRST" ] || [ -z "$LAST" ]; then
    echo "error: could not locate the Granulator class in $SOURCE" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<'HEADER'
// GENERATED FILE -- DO NOT EDIT.
//
// The Granulator DSP class from the LV2 build in
// CppSrc/Granulator_linux_lv2-32bits.cpp, which was produced by Faust 2.0.a40
// in 2016 and is the build running on the MOD. It is extracted verbatim by
// Plugins/tools/extract-lv2-reference.sh and used as the reference the current
// Faust output is compared against, so that regenerating the DSP with a newer
// compiler cannot silently change how the plugin sounds.
//
// Everything outside the `oldgran` namespace body below is shim: the original
// architecture file supplied these declarations.

#pragma once

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif

#include <algorithm>
#include <cmath>
#include <cstdlib>

namespace oldgran {

inline int   max (int a, int b)     { return a > b ? a : b; }
inline int   min (int a, int b)     { return a < b ? a : b; }
inline float max (float a, float b) { return a > b ? a : b; }
inline float min (float a, float b) { return a < b ? a : b; }

struct Meta { virtual ~Meta() {} virtual void declare (const char*, const char*) {} };

struct UI
{
    virtual ~UI() {}
    virtual void openVerticalBox (const char*) {}
    virtual void openHorizontalBox (const char*) {}
    virtual void closeBox() {}
    virtual void declare (float*, const char*, const char*) {}
    virtual void addHorizontalSlider (const char*, float* zone, float init, float, float, float) { *zone = init; }
    virtual void addVerticalSlider (const char*, float* zone, float init, float, float, float) { *zone = init; }
    virtual void addNumEntry (const char*, float* zone, float init, float, float, float) { *zone = init; }
};

class dsp
{
 protected:
    int fSamplingFreq;
 public:
    dsp() {}
    virtual ~dsp() {}
    virtual int getNumInputs() = 0;
    virtual int getNumOutputs() = 0;
    virtual void buildUserInterface (UI* interface) = 0;
    virtual void init (int samplingRate) = 0;
    virtual void compute (int len, float** inputs, float** outputs) = 0;
};

HEADER

sed -n "${FIRST},${LAST}p" "$SOURCE" >> "$OUTPUT"

echo '' >> "$OUTPUT"
echo '} // namespace oldgran' >> "$OUTPUT"

echo "Wrote $OUTPUT ($(wc -l < "$OUTPUT") lines, from lines $FIRST-$LAST of CppSrc)"
